management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/